#!/usr/bin/env python3
"""Generate the release-notes pages of the documentation site (chatcli.ai)
from release-please's CHANGELOG.md.

usage: gen-release-notes.py --changelog CHANGELOG.md --docs /path/to/chatcli.ai

The output is fully derived and rewritten on every run, so the script is
idempotent and safe to re-run after any release:

  releases.mdx, pt/releases.mdx            the index of every release
  releases/<X.Y.Z>.mdx, pt/releases/...    one page per release
  index.mdx, pt/index.mdx                  the "New release" strip, between
                                           the release-strip markers
  docs.json                                the Releases sidebar group

Release notes are written in English by the commit authors; the Portuguese
pages translate the page chrome and keep the entries as written.
"""
import argparse
import datetime
import json
import os
import re
import sys

REPO = "https://github.com/diillson/chatcli"
SIDEBAR_RELEASES = 10  # newest releases listed in the sidebar

HEADING = re.compile(r"^## \[(\d+\.\d+\.\d+)\]\((\S+)\) \((\d{4}-\d{2}-\d{2})\)\s*$")
SECTION = re.compile(r"^### (.+?)\s*$")
BULLET = re.compile(r"^\* (.*)$")
SCOPED = re.compile(r"^\*\*([^*]+?):\*\* (.*)$")
# release-please appends "([#123](url))", "([abc1234](url))" and
# ", closes [#1](url) [#2](url)" to each entry.
PR_REF = re.compile(r"\(\[#(\d+)\]\((\S+?)\)\)")
SHA_REF = re.compile(r"\(\[([0-9a-f]{7,40})\]\((\S+?)\)\)")
CLOSES = re.compile(r",? closes (?:\[#\d+\]\(\S+?\)[ ,]*)+$")

# Section headings, in display order, with their labels.
KINDS = [
    ("breaking", ("⚠ BREAKING CHANGES",), "Breaking changes", "Mudanças incompatíveis"),
    ("features", ("Features",), "New features", "Novidades"),
    ("fixes", ("Bug Fixes",), "Fixes", "Correções"),
    ("perf", ("Performance Improvements",), "Performance", "Desempenho"),
    ("docs", ("Documentation",), "Documentation", "Documentação"),
    ("other", (), "Other changes", "Outras mudanças"),
]

# Commit scope -> documentation page. A scope chip links to its page only
# when the page exists in the docs tree; unknown scopes render as plain chips.
SCOPE_PAGES = {
    "acp": "server/acp",
    "agent": "usage/agent-mode",
    "aiops": "kubernetes/aiops-platform",
    "api-explorer": "tools/api-explorer",
    "auth": "providers/oauth-authentication",
    "bedrock": "providers/bedrock",
    "browser": "tools/browser-automation",
    "catalog": "providers/supported-models",
    "coder": "usage/coder-mode",
    "config": "reference/configuration",
    "context": "context/persistent-context",
    "cost": "providers/cost-tracking",
    "dash": "usage/live-dashboard",
    "devin": "providers/devin-provider",
    "diagram": "tools/diagram",
    "eval": "agents/harness/evals",
    "forge": "tools/git-forge",
    "gateway": "gateway/chat-gateway",
    "graphview": "tools/graphview",
    "help": "reference/command-reference",
    "helm": "kubernetes/artifacthub",
    "hooks": "extensions/hooks-system",
    "i18n": "usage/i18n",
    "image": "tools/image-generation",
    "knowledge": "context/knowledge-base",
    "lsp": "coder/lsp-diagnostics",
    "mcp": "extensions/mcp-integration",
    "memory": "context/bootstrap-memory",
    "models": "providers/supported-models",
    "operator": "kubernetes/k8s-operator",
    "plugins": "extensions/plugin-system",
    "pulsedash": "usage/live-dashboard",
    "quality": "agents/harness/overview",
    "scheduler": "tools/scheduler",
    "security": "security/overview",
    "server": "server/server-mode",
    "session": "context/session-management",
    "skills": "extensions/skill-registry",
    "squad": "agents/agent-squad",
    "taskgraph": "agents/task-graph",
    "update": "start/auto-update",
    "web": "usage/web-ui",
    "webfetch": "tools/web-tools",
    "websearch": "tools/web-tools",
    "worktree": "coder/worktrees",
}

PT_MONTHS = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho",
             "agosto", "setembro", "outubro", "novembro", "dezembro"]
EN_MONTHS = ["January", "February", "March", "April", "May", "June", "July",
             "August", "September", "October", "November", "December"]

MARK_START = "{/* release-strip:start */}"
MARK_END = "{/* release-strip:end */}"
GENERATED = ("{/* Generated by scripts/docs/gen-release-notes.py in the chatcli repo "
             "from its CHANGELOG.md. Edits here are overwritten on the next release. */}")


# ---------------------------------------------------------------- parsing --

def parse(text):
    """Return releases newest first: dicts with version, compare, date and
    entries per kind (each entry: scope, message, prs, shas)."""
    releases = []
    cur = None
    kind = None
    for line in text.splitlines():
        m = HEADING.match(line)
        if m:
            # release-please occasionally writes a release section twice;
            # the copies merge into one release.
            cur = next((r for r in releases if r["version"] == m.group(1)), None)
            if cur is None:
                cur = {"version": m.group(1), "compare": m.group(2), "date": m.group(3),
                       "entries": {k[0]: [] for k in KINDS}}
                releases.append(cur)
            kind = None
            continue
        if cur is None:
            continue
        m = SECTION.match(line)
        if m:
            title = m.group(1)
            kind = next((k[0] for k in KINDS if title in k[1]), "other")
            continue
        m = BULLET.match(line)
        if m and kind:
            e = parse_entry(m.group(1))
            if all((x["scope"], x["message"]) != (e["scope"], e["message"]) for x in cur["entries"][kind]):
                cur["entries"][kind].append(e)
            continue
        if line.strip() and kind and cur["entries"][kind] and not line.startswith("#"):
            # a wrapped continuation of the previous entry
            e = cur["entries"][kind][-1]
            e["message"] = (e["message"] + " " + line.strip()).strip()
    return releases


# release-please turns "@name" into a GitHub user link; in ChatCLI those are
# tool names (@kind, @coder), so the link is dropped.
MENTION = re.compile(r"\[(@[A-Za-z0-9_-]+)\]\(https://github\.com/[A-Za-z0-9_-]+\)")
CONTROL = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")


def parse_entry(raw):
    s = CONTROL.sub(" ", raw.strip())
    s = MENTION.sub(r"\1", s)
    s = CLOSES.sub("", s)
    prs = [(n, u) for n, u in PR_REF.findall(s)]
    shas = [(h, u) for h, u in SHA_REF.findall(s)]
    s = PR_REF.sub("", s)
    s = SHA_REF.sub("", s).strip()
    scope = None
    m = SCOPED.match(s)
    if m:
        scope, s = m.group(1).strip(), m.group(2).strip()
    return {"scope": scope, "message": s.rstrip(), "prs": prs, "shas": shas}


# ------------------------------------------------------------- rendering --

FLAG = re.compile(r"(?<![\w`-])(--[A-Za-z][\w-]*(?:=\S+)?)")


def mdx_text(s):
    """Escape MDX-significant characters outside inline code spans. A bare
    --flag becomes code, or the site's typography would turn "--" into a dash."""
    parts = re.split(r"(`[^`]*`)", s)
    parts = [p if p.startswith("`") else FLAG.sub(r"`\1`", p) for p in parts]
    parts = re.split(r"(`[^`]*`)", "".join(parts))
    out = []
    for p in parts:
        if p.startswith("`") and p.endswith("`") and len(p) > 1:
            out.append(p)
        else:
            out.append(p.replace("\\", "\\\\").replace("{", "&#123;").replace("}", "&#125;")
                       .replace("<", "&lt;").replace(">", "&gt;"))
    return "".join(out)


def plain(s):
    """A message as plain text for frontmatter and the home strip. "--" is
    written with non-breaking hyphens so typography never merges it into a
    dash."""
    s = s.replace("`", "").replace("--", "\u2011\u2011")
    return re.sub(r"\s+", " ", s).strip()


def jsx_text(s):
    return plain(s).replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;").replace(">", "&gt;")


def yaml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def capitalize(s):
    return s[:1].upper() + s[1:] if s else s


def summary(rel, lang):
    """One line: the headline features (or fixes), for the index and the strip."""
    e = rel["entries"]
    lead = e["breaking"] + e["features"] or e["fixes"] or e["perf"] or e["docs"] or e["other"]
    heads = [plain(x["message"]).rstrip(".") for x in lead[:3]]
    text = "; ".join(heads)
    if len(text) > 180:
        text = text[:177].rsplit(" ", 1)[0] + "…"
    return text or ("Maintenance release." if lang == "en" else "Release de manutenção.")


def counts(rel, lang):
    e = rel["entries"]
    nf, nx = len(e["features"]), len(e["fixes"])
    parts = []
    if lang == "en":
        if nf:
            parts.append(f"{nf} new feature" + ("s" if nf != 1 else ""))
        if nx:
            parts.append(f"{nx} fix" + ("es" if nx != 1 else ""))
        rest = sum(len(e[k]) for k in ("breaking", "perf", "docs", "other"))
        if rest:
            parts.append(f"{rest} other change" + ("s" if rest != 1 else ""))
        return " · ".join(parts)
    if nf:
        parts.append(f"{nf} novidade" + ("s" if nf != 1 else ""))
    if nx:
        parts.append(f"{nx} correç" + ("ões" if nx != 1 else "ão"))
    rest = sum(len(e[k]) for k in ("breaking", "perf", "docs", "other"))
    if rest:
        parts.append(f"{rest} outra" + ("s" if rest != 1 else "") + " mudança" + ("s" if rest != 1 else ""))
    return " · ".join(parts)


def date_label(iso, lang):
    d = datetime.date.fromisoformat(iso)
    if lang == "en":
        return f"{EN_MONTHS[d.month - 1]} {d.day}, {d.year}"
    return f"{d.day} de {PT_MONTHS[d.month - 1]} de {d.year}"


def scope_chip(scope, lang, docs_root):
    label = mdx_text(scope)
    page = SCOPE_PAGES.get(scope)
    if page:
        rel = ("pt/" if lang == "pt" else "") + page
        if os.path.exists(os.path.join(docs_root, rel + ".mdx")):
            return f'<a className="cc-scope" href="/{rel}">{label}</a>'
    return f'<span className="cc-scope">{label}</span>'


def entry_line(e, lang, docs_root):
    chip = scope_chip(e["scope"], lang, docs_root) + " " if e["scope"] else ""
    refs = [f"[#{n}]({u})" for n, u in e["prs"]] + [f"[{h}]({u})" for h, u in e["shas"]]
    tail = f' <span className="cc-refs">{" · ".join(refs)}</span>' if refs else ""
    return f"- {chip}{mdx_text(e['message'])}{tail}"


def render_release(rel, prev, nxt, latest, lang, docs_root):
    pre = "/pt" if lang == "pt" else ""
    v = rel["version"]
    tag_url = f"{REPO}/releases/tag/v{v}"
    lines = ["---",
             f'title: "v{v}"',
             f"description: {yaml_str(summary(rel, lang))}"]
    if latest:
        lines.append('tag: "Latest"' if lang == "en" else 'tag: "Mais recente"')
    lines += ["---", "", GENERATED, ""]
    released = "Released" if lang == "en" else "Lançada em"
    gh = "GitHub release" if lang == "en" else "Release no GitHub"
    cmp_ = "Compare changes" if lang == "en" else "Comparar mudanças"
    lines.append('<div className="cc-release-meta">')
    lines.append(f"  <span>{released} {date_label(rel['date'], lang)}</span>")
    c = counts(rel, lang)
    if c:
        lines.append(f"  <span>{c}</span>")
    lines.append(f'  <a href="{tag_url}">{gh}</a>')
    lines.append(f'  <a href="{rel["compare"]}">{cmp_}</a>')
    lines.append("</div>")
    lines.append("")
    if lang == "pt":
        lines += ["<Note>", "As entradas vêm do changelog do projeto e ficam em inglês, como foram escritas nos commits.", "</Note>", ""]
    for key, _, en_label, pt_label in KINDS:
        items = rel["entries"][key]
        if not items:
            continue
        lines.append(f"## {en_label if lang == 'en' else pt_label}")
        lines.append("")
        if key == "breaking":
            lines.append("<Warning>")
            lines.append("Read these before you upgrade." if lang == "en" else "Leia antes de atualizar.")
            lines.append("</Warning>")
            lines.append("")
        lines += [entry_line(e, lang, docs_root) for e in items]
        lines.append("")
    cards = []
    if nxt:
        t = "Newer release" if lang == "en" else "Release mais nova"
        cards.append(f'  <Card title="{t}: v{nxt["version"]}" icon="arrow-left" href="{pre}/releases/{nxt["version"]}">\n'
                     f"    {jsx_text(summary(nxt, lang))}\n  </Card>")
    if prev:
        t = "Previous release" if lang == "en" else "Release anterior"
        cards.append(f'  <Card title="{t}: v{prev["version"]}" icon="arrow-right" href="{pre}/releases/{prev["version"]}">\n'
                     f"    {jsx_text(summary(prev, lang))}\n  </Card>")
    if cards:
        lines += ["---", "", "<CardGroup cols={2}>"] + cards + ["</CardGroup>", ""]
    return "\n".join(lines)


def render_index(releases, lang):
    pre = "/pt" if lang == "pt" else ""
    if lang == "en":
        head = ["---", 'title: "Release notes"',
                'description: "What changed in every ChatCLI release, newest first, with links to the pull requests and commits."',
                'icon: "tag"', "---", "", GENERATED, "",
                "Each release has its own page with the new features, fixes and links to the source changes. "
                f"The same notes ship on [GitHub Releases]({REPO}/releases), and the full history is in "
                f"[CHANGELOG.md]({REPO}/blob/main/CHANGELOG.md).", ""]
    else:
        head = ["---", 'title: "Notas de release"',
                'description: "O que mudou em cada release do ChatCLI, da mais nova para a mais antiga, com links para os pull requests e commits."',
                'icon: "tag"', "---", "", GENERATED, "",
                "Cada release tem uma página própria com as novidades, as correções e os links para as mudanças no código. "
                f"As mesmas notas saem no [GitHub Releases]({REPO}/releases), e o histórico completo está no "
                f"[CHANGELOG.md]({REPO}/blob/main/CHANGELOG.md).", ""]
    latest = releases[0]
    title = "Latest release" if lang == "en" else "Release mais recente"
    head += [f'<Card title="{title}: v{latest["version"]}" icon="sparkles" href="{pre}/releases/{latest["version"]}">',
             f"  {date_label(latest['date'], lang)} · {jsx_text(summary(latest, lang))}", "</Card>", ""]
    body = []
    year = month = None
    for idx, r in enumerate(releases):
        d = datetime.date.fromisoformat(r["date"])
        if d.year != year:
            year, month = d.year, None
            body += [f"## {year}", ""]
        if d.month != month:
            month = d.month
            name = EN_MONTHS[month - 1] if lang == "en" else capitalize(PT_MONTHS[month - 1])
            body += [f"### {name}", ""]
        body.append(f"- [**v{r['version']}**]({pre}/releases/{r['version']}) — {mdx_text(summary(r, lang))}")
        # a blank line closes each month's list
        last_of_month = idx + 1 == len(releases)
        if not last_of_month:
            nd = datetime.date.fromisoformat(releases[idx + 1]["date"])
            last_of_month = (nd.year, nd.month) != (d.year, d.month)
        if last_of_month:
            body.append("")
    return "\n".join(head + body).rstrip() + "\n"


def render_strip(rel, lang):
    pre = "/pt" if lang == "pt" else ""
    label = "New release" if lang == "en" else "Nova release"
    cta = "Read release notes →" if lang == "en" else "Ler as notas →"
    return (f'<a className="cc-release" href="{pre}/releases/{rel["version"]}">'
            f'<span className="cc-release-label">{label}</span>'
            f'<span className="cc-release-version">v{rel["version"]}</span>'
            f'<span className="cc-release-summary">{jsx_text(summary(rel, lang))}</span>'
            f'<span className="cc-release-cta">{cta}</span></a>')


# ----------------------------------------------------------------- output --

def write(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        return 1
    return 0


def update_strip(path, strip):
    s = open(path, encoding="utf-8").read()
    i, j = s.find(MARK_START), s.find(MARK_END)
    if i < 0 or j < i:
        sys.exit(f"{path}: release-strip markers not found")
    new = s[:i + len(MARK_START)] + "\n" + strip + "\n" + s[j:]
    return write(path, new)


def update_nav(docs_root, releases):
    path = os.path.join(docs_root, "docs.json")
    d = json.load(open(path, encoding="utf-8"))
    found = 0

    def walk(node, pre):
        nonlocal found
        if isinstance(node, dict):
            pages = node.get("pages")
            if isinstance(pages, list) and pre + "releases" in pages:
                node["pages"] = [pre + "releases"] + [pre + "releases/" + r["version"]
                                                      for r in releases[:SIDEBAR_RELEASES]]
                # the sidebar shows the newest version next to the group name
                node["tag"] = "v" + releases[0]["version"]
                found += 1
                return
            for k in ("groups", "pages", "tabs"):
                for c in node.get(k, []) or []:
                    walk(c, pre)

    for lang in d["navigation"]["languages"]:
        walk(lang, "pt/" if lang["language"].startswith("pt") else "")
    if found != 2:
        sys.exit(f"docs.json: expected the Releases group in both languages, found {found}")
    text = json.dumps(d, indent=2, ensure_ascii=False) + "\n"
    return write(path, text)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--changelog", required=True)
    ap.add_argument("--docs", required=True, help="root of the chatcli.ai docs repo")
    a = ap.parse_args()
    releases = parse(open(a.changelog, encoding="utf-8").read())
    if not releases:
        sys.exit("no releases found in " + a.changelog)
    root = a.docs
    changed = 0
    for lang, pre in (("en", ""), ("pt", "pt/")):
        out_dir = os.path.join(root, pre + "releases")
        keep = set()
        for i, r in enumerate(releases):
            nxt = releases[i - 1] if i > 0 else None
            prev = releases[i + 1] if i + 1 < len(releases) else None
            name = r["version"] + ".mdx"
            keep.add(name)
            changed += write(os.path.join(out_dir, name), render_release(r, prev, nxt, i == 0, lang, root))
        # a version removed from the changelog loses its page
        for f in os.listdir(out_dir):
            if f.endswith(".mdx") and f not in keep:
                os.remove(os.path.join(out_dir, f))
                changed += 1
        changed += write(os.path.join(root, pre + "releases.mdx"), render_index(releases, lang))
        changed += update_strip(os.path.join(root, pre + "index.mdx"), render_strip(releases[0], lang))
    changed += update_nav(root, releases)
    print(f"release notes: {len(releases)} releases, latest v{releases[0]['version']}, {changed} file(s) changed")


if __name__ == "__main__":
    main()
