//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatCLIInstance) DeepCopyInto(out *ChatCLIInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatCLIInstance.
func (in *ChatCLIInstance) DeepCopy() *ChatCLIInstance {
	if in == nil {
		return nil
	}
	out := new(ChatCLIInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChatCLIInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatCLIInstanceList) DeepCopyInto(out *ChatCLIInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChatCLIInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatCLIInstanceList.
func (in *ChatCLIInstanceList) DeepCopy() *ChatCLIInstanceList {
	if in == nil {
		return nil
	}
	out := new(ChatCLIInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChatCLIInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ChatCLIInstanceSpec) DeepCopyInto(out *ChatCLIInstanceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Image = in.Image
	in.Server.DeepCopyInto(&out.Server)
	if in.Watcher != nil {
		in, out := &in.Watcher, &out.Watcher
		*out = new(WatcherSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKeys != nil {
		in, out := &in.APIKeys, &out.APIKeys
		*out = new(SecretRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ChatCLIInstanceSpec) DeepCopy() *ChatCLIInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ChatCLIInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ChatCLIInstanceStatus) DeepCopyInto(out *ChatCLIInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ChatCLIInstanceStatus) DeepCopy() *ChatCLIInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ChatCLIInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ServerSpec) DeepCopyInto(out *ServerSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(SecretKeyRefSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServerSpec) DeepCopy() *ServerSpec {
	if in == nil {
		return nil
	}
	out := new(ServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	*out = *in
	return out
}

func (in *SecretKeyRefSpec) DeepCopyInto(out *SecretKeyRefSpec) {
	*out = *in
}

func (in *SecretKeyRefSpec) DeepCopy() *SecretKeyRefSpec {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRefSpec)
	*out = *in
	return out
}

func (in *SecretRefSpec) DeepCopyInto(out *SecretRefSpec) {
	*out = *in
}

func (in *SecretRefSpec) DeepCopy() *SecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(SecretRefSpec)
	*out = *in
	return out
}

func (in *WatcherSpec) DeepCopyInto(out *WatcherSpec) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]WatchTargetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *WatcherSpec) DeepCopy() *WatcherSpec {
	if in == nil {
		return nil
	}
	out := new(WatcherSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WatchTargetSpec) DeepCopyInto(out *WatchTargetSpec) {
	*out = *in
	if in.MetricsFilter != nil {
		in, out := &in.MetricsFilter, &out.MetricsFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *WatchTargetSpec) DeepCopy() *WatchTargetSpec {
	if in == nil {
		return nil
	}
	out := new(WatchTargetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PersistenceSpec) DeepCopyInto(out *PersistenceSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

func (in *PersistenceSpec) DeepCopy() *PersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(PersistenceSpec)
	in.DeepCopyInto(out)
	return out
}
