// ChatCLI gRPC Service Definition
// Copyright (c) 2024 Edilson Freitas
// License: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: proto/chatcli/v1/chatcli.proto

package chatcliv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatCLIService_SendPrompt_FullMethodName         = "/chatcli.v1.ChatCLIService/SendPrompt"
	ChatCLIService_StreamPrompt_FullMethodName       = "/chatcli.v1.ChatCLIService/StreamPrompt"
	ChatCLIService_InteractiveSession_FullMethodName = "/chatcli.v1.ChatCLIService/InteractiveSession"
	ChatCLIService_ListSessions_FullMethodName       = "/chatcli.v1.ChatCLIService/ListSessions"
	ChatCLIService_LoadSession_FullMethodName        = "/chatcli.v1.ChatCLIService/LoadSession"
	ChatCLIService_SaveSession_FullMethodName        = "/chatcli.v1.ChatCLIService/SaveSession"
	ChatCLIService_DeleteSession_FullMethodName      = "/chatcli.v1.ChatCLIService/DeleteSession"
	ChatCLIService_GetServerInfo_FullMethodName      = "/chatcli.v1.ChatCLIService/GetServerInfo"
	ChatCLIService_GetWatcherStatus_FullMethodName   = "/chatcli.v1.ChatCLIService/GetWatcherStatus"
	ChatCLIService_Health_FullMethodName             = "/chatcli.v1.ChatCLIService/Health"
)

// ChatCLIServiceClient is the client API for ChatCLIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatCLIService exposes ChatCLI functionality over gRPC.
type ChatCLIServiceClient interface {
	// SendPrompt sends a single prompt and returns the LLM response (one-shot mode).
	SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...grpc.CallOption) (*SendPromptResponse, error)
	// StreamPrompt sends a prompt and streams back the response chunks.
	StreamPrompt(ctx context.Context, in *StreamPromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPromptResponse], error)
	// InteractiveSession opens a bidirectional stream for interactive/agent mode.
	InteractiveSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error)
	// ListSessions returns all saved session names.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// LoadSession loads a previously saved session's message history.
	LoadSession(ctx context.Context, in *LoadSessionRequest, opts ...grpc.CallOption) (*LoadSessionResponse, error)
	// SaveSession saves the current conversation history.
	SaveSession(ctx context.Context, in *SaveSessionRequest, opts ...grpc.CallOption) (*SaveSessionResponse, error)
	// DeleteSession removes a saved session.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// GetServerInfo returns server metadata (provider, model, version).
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	// GetWatcherStatus returns the K8s watcher status (if active).
	GetWatcherStatus(ctx context.Context, in *GetWatcherStatusRequest, opts ...grpc.CallOption) (*GetWatcherStatusResponse, error)
	// Health check for load balancers and k8s probes.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type chatCLIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatCLIServiceClient(cc grpc.ClientConnInterface) ChatCLIServiceClient {
	return &chatCLIServiceClient{cc}
}

func (c *chatCLIServiceClient) SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...grpc.CallOption) (*SendPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPromptResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_SendPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) StreamPrompt(ctx context.Context, in *StreamPromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPromptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatCLIService_ServiceDesc.Streams[0], ChatCLIService_StreamPrompt_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPromptRequest, StreamPromptResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCLIService_StreamPromptClient = grpc.ServerStreamingClient[StreamPromptResponse]

func (c *chatCLIServiceClient) InteractiveSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatCLIService_ServiceDesc.Streams[1], ChatCLIService_InteractiveSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionMessage, SessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCLIService_InteractiveSessionClient = grpc.BidiStreamingClient[SessionMessage, SessionMessage]

func (c *chatCLIServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) LoadSession(ctx context.Context, in *LoadSessionRequest, opts ...grpc.CallOption) (*LoadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadSessionResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_LoadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) SaveSession(ctx context.Context, in *SaveSessionRequest, opts ...grpc.CallOption) (*SaveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSessionResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_SaveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) GetWatcherStatus(ctx context.Context, in *GetWatcherStatusRequest, opts ...grpc.CallOption) (*GetWatcherStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWatcherStatusResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_GetWatcherStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCLIServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ChatCLIService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatCLIServiceServer is the server API for ChatCLIService service.
// All implementations must embed UnimplementedChatCLIServiceServer
// for forward compatibility.
//
// ChatCLIService exposes ChatCLI functionality over gRPC.
type ChatCLIServiceServer interface {
	// SendPrompt sends a single prompt and returns the LLM response (one-shot mode).
	SendPrompt(context.Context, *SendPromptRequest) (*SendPromptResponse, error)
	// StreamPrompt sends a prompt and streams back the response chunks.
	StreamPrompt(*StreamPromptRequest, grpc.ServerStreamingServer[StreamPromptResponse]) error
	// InteractiveSession opens a bidirectional stream for interactive/agent mode.
	InteractiveSession(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error
	// ListSessions returns all saved session names.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// LoadSession loads a previously saved session's message history.
	LoadSession(context.Context, *LoadSessionRequest) (*LoadSessionResponse, error)
	// SaveSession saves the current conversation history.
	SaveSession(context.Context, *SaveSessionRequest) (*SaveSessionResponse, error)
	// DeleteSession removes a saved session.
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// GetServerInfo returns server metadata (provider, model, version).
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	// GetWatcherStatus returns the K8s watcher status (if active).
	GetWatcherStatus(context.Context, *GetWatcherStatusRequest) (*GetWatcherStatusResponse, error)
	// Health check for load balancers and k8s probes.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedChatCLIServiceServer()
}

// UnimplementedChatCLIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatCLIServiceServer struct{}

func (UnimplementedChatCLIServiceServer) SendPrompt(context.Context, *SendPromptRequest) (*SendPromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrompt not implemented")
}
func (UnimplementedChatCLIServiceServer) StreamPrompt(*StreamPromptRequest, grpc.ServerStreamingServer[StreamPromptResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPrompt not implemented")
}
func (UnimplementedChatCLIServiceServer) InteractiveSession(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error {
	return status.Errorf(codes.Unimplemented, "method InteractiveSession not implemented")
}
func (UnimplementedChatCLIServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedChatCLIServiceServer) LoadSession(context.Context, *LoadSessionRequest) (*LoadSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSession not implemented")
}
func (UnimplementedChatCLIServiceServer) SaveSession(context.Context, *SaveSessionRequest) (*SaveSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSession not implemented")
}
func (UnimplementedChatCLIServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedChatCLIServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedChatCLIServiceServer) GetWatcherStatus(context.Context, *GetWatcherStatusRequest) (*GetWatcherStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWatcherStatus not implemented")
}
func (UnimplementedChatCLIServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedChatCLIServiceServer) mustEmbedUnimplementedChatCLIServiceServer() {}
func (UnimplementedChatCLIServiceServer) testEmbeddedByValue()                        {}

// UnsafeChatCLIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatCLIServiceServer will
// result in compilation errors.
type UnsafeChatCLIServiceServer interface {
	mustEmbedUnimplementedChatCLIServiceServer()
}

func RegisterChatCLIServiceServer(s grpc.ServiceRegistrar, srv ChatCLIServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatCLIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatCLIService_ServiceDesc, srv)
}

func _ChatCLIService_SendPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).SendPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_SendPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).SendPrompt(ctx, req.(*SendPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_StreamPrompt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPromptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatCLIServiceServer).StreamPrompt(m, &grpc.GenericServerStream[StreamPromptRequest, StreamPromptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCLIService_StreamPromptServer = grpc.ServerStreamingServer[StreamPromptResponse]

func _ChatCLIService_InteractiveSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatCLIServiceServer).InteractiveSession(&grpc.GenericServerStream[SessionMessage, SessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCLIService_InteractiveSessionServer = grpc.BidiStreamingServer[SessionMessage, SessionMessage]

func _ChatCLIService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_LoadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).LoadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_LoadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).LoadSession(ctx, req.(*LoadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_SaveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).SaveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_SaveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).SaveSession(ctx, req.(*SaveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_GetWatcherStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatcherStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).GetWatcherStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_GetWatcherStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).GetWatcherStatus(ctx, req.(*GetWatcherStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCLIService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCLIServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCLIService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCLIServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatCLIService_ServiceDesc is the grpc.ServiceDesc for ChatCLIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatCLIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatcli.v1.ChatCLIService",
	HandlerType: (*ChatCLIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrompt",
			Handler:    _ChatCLIService_SendPrompt_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _ChatCLIService_ListSessions_Handler,
		},
		{
			MethodName: "LoadSession",
			Handler:    _ChatCLIService_LoadSession_Handler,
		},
		{
			MethodName: "SaveSession",
			Handler:    _ChatCLIService_SaveSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _ChatCLIService_DeleteSession_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _ChatCLIService_GetServerInfo_Handler,
		},
		{
			MethodName: "GetWatcherStatus",
			Handler:    _ChatCLIService_GetWatcherStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ChatCLIService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPrompt",
			Handler:       _ChatCLIService_StreamPrompt_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InteractiveSession",
			Handler:       _ChatCLIService_InteractiveSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/chatcli/v1/chatcli.proto",
}
