name: Go Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true  # Habilitar cache para dependências

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --timeout=5m  # Mover timeout para args

      - name: Lint
        run: golangci-lint run

      - name: Check gofmt
        run: |
          output=$(gofmt -l .)
          if [ -n "$output" ]; then
            echo "::error file=gofmt::The following files are not formatted:"
            echo "$output"
            exit 1
          fi

      - name: Run unit tests
        run: go test ./... -v
  