name: Open PR develop -> main

on:
  push:
    branches: [develop]

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: open-pr-develop-to-main
  cancel-in-progress: true

jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Open or reuse PR develop -> main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_RELEASE_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = `${owner}:develop`;
            const base = 'main';
            
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head, base, per_page: 10
            });
            
            if (prs.length > 0) {
              core.info(`PR já existe: #${prs[0].number}`);
              return;
            }
            
            const title = `Merge develop into main`;
            const body  = `PR automático para promover mudanças da develop à main.`;
            
            const { data: pr } = await github.rest.pulls.create({
              owner, repo, head: 'develop', base, title, body
            });
            
            core.info(`PR criado: #${pr.number}`);