name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build binaries
        run: |
          # COMMIT=$(git rev-parse HEAD)
          # BUILD_TIME=$(date -u +'%Y-%m-%d %H:%M:%S')
          # LDFLAGS="-X 'github.com/diillson/chatcli/pkg/version.Commit=${COMMIT}' -X 'github.com/diillson/chatcli/pkg/version.BuildTime=${BUILD_TIME}'"
          # Build para várias plataformas
          GOOS=linux GOARCH=amd64 go build -o chatcli-linux-amd64 ./main.go
          GOOS=darwin GOARCH=amd64 go build -o chatcli-darwin-amd64 ./main.go
          GOOS=windows GOARCH=amd64 go build -o chatcli-windows-amd64.exe ./main.go
          # Verifica a versão do binário
          # ./chatcli-linux-amd64 --version

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            chatcli-linux-amd64
            chatcli-darwin-amd64
            chatcli-windows-amd64.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN}}