name: Sync main to develop

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  sync:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-please--branches--main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura usuário git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/diillson/chatcli.git"

      - name: Merge main into develop
        run: |
          git checkout develop
          git merge main --no-ff --no-edit
          git push origin develop