name: Sync main to develop

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          fetch-depth: 0

      - name: Configura usuário git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into develop
        run: |
          git checkout develop
          git pull origin develop
          git merge main --no-ff --no-edit -m "chore: merge main back into develop after release"
          git push origin develop